POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Add blog for admin",
    "author": "Blog author test",
    "url": "http://test//blog",
    "likes": 1,
    "userId": "648f4f3e363009798edab95a"
}